# Basic parameters
seed: 1000
data_folder: !PLACEHOLDER
output_folder: !ref results/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Training params
N_epochs: 40
lr: 0.001
dataloader_options:
    batch_size: 32

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
   limit: !ref <N_epochs>
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_log>

# Feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# Number of speakers
num_spks: 250

# Add noise
add_noise: !new:speechbrain.processing.speech_augmentation.AddNoise
    csv_file: !ref <data_folder>/annotation/noise.csv
    sorting: descending
    snr_low: 0
    snr_high: 0
    pad_noise: False
    start_index: 0
    replacements:
        noise_folder: !ref <data_folder>/noise

compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

xvector_model: !new:speechbrain.lobes.models.Xvector.Xvector
    in_channels: !ref <n_mels>
    activation: !name:torch.nn.LeakyReLU
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: 512

classifier: !new:speechbrain.lobes.models.Xvector.Classifier
    input_shape: [null, null, 512]
    activation: !name:torch.nn.LeakyReLU
    lin_blocks: 1
    lin_neurons: 512
    out_neurons: !ref <num_spks>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

modules:
    compute_features: !ref <compute_features>
    xvector_model: !ref <xvector_model>
    classifier: !ref <classifier>
    mean_var_norm: !ref <mean_var_norm>

model: !new:torch.nn.ModuleList
   - [!ref <compute_features>, !ref <xvector_model>, !ref <classifier>]

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_folder>
   recoverables:
      model: !ref <model>
      counter: !ref <epoch_counter>
      normalizer: !ref <mean_var_norm>

compute_cost: !name:speechbrain.nnet.losses.nll_loss
acc_computer: !name:speechbrain.utils.Accuracy.AccuracyStats

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

