# Basic parameters
seed: 1234
data_folder: !PLACEHOLDER
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Training params
N_epochs: 10
lr: 0.001
dataloader_options:
    batch_size: 64

# Feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# Number of speakers
num_spks: 250

# Add noise
add_noise: !new:speechbrain.processing.speech_augmentation.AddNoise
    csv_file: !ref <data_folder>/annotation/noise.csv
    sorting: descending
    snr_low: 0
    snr_high: 0
    pad_noise: False
    start_index: 0
    replacements:
        noise_folder: !ref <data_folder>/noise

compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

xvector_model: !new:speechbrain.lobes.models.Xvector.Xvector
    in_channels: !ref <n_mels>
    activation: !name:torch.nn.LeakyReLU
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: 512

classifier: !new:speechbrain.lobes.models.Xvector.Classifier
    input_shape: [null, null, 512]
    activation: !name:torch.nn.LeakyReLU
    lin_blocks: 1
    lin_neurons: 512
    out_neurons: !ref <num_spks>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

modules:
    compute_features: !ref <compute_features>
    xvector_model: !ref <xvector_model>
    classifier: !ref <classifier>
    mean_var_norm: !ref <mean_var_norm>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

compute_cost: !name:speechbrain.nnet.losses.nll_loss

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

acc_computer: !name:speechbrain.utils.Accuracy.AccuracyStats
